bbs/forum/urls.py
from django.conf.urls import patterns, include, url


api_urlpatterns = patterns('bbs.forum.api',
    url(r'^topic/(?P<topic_id>\d+)/$', 'topic_api', name='topic_api'),
    url(r'^topics/$', 'topics_api', name='topics_api'),
    url(r'^post/(?P<post_id>\d+)/$', 'post_api', name='post_api'),
    url(r'^/simditor-upload/$', 'simditor_upload', name='simditor_upload'),
)


urlpatterns = patterns('bbs.forum.views', url(r'^$', 'index', name='bbsindex'),

    url(r'^topic/(?P<topic_id>\d+)/$', 'topic_view', name='topic_view'),
    url(r'^topic/(?P<topic_id>\d+)/reply/$', 'create_reply', name='create_reply'),
    url(r'^topic/(?P<topic_id>\d+)/append/$', 'add_appendix', name='add_appendix'),
    url(r'^topic/(?P<topic_id>\d+)/delete/$', 'del_topic', name='delete_topic'),
    url(r'^topic/(?P<topic_id>\d+)/edit/$', 'edit_topic', name='edit_topic'),
    url(r'^post/(?P<post_id>\d+)/delete/$', 'del_reply', name='delete_post'),
    url(r'^node/$', 'node_all', name='node_all'),
    url(r'^topic1/(?P<topic_id>\d+)/$', 'collect_topic', name='collect_topic'),
    url(r'^node/(?P<node_id>\d+)/$', 'node_view', name='node_view'),
    #url(r'^node-list/(?P<theme_id>\d+)/$', 'node_list', name='node_list'),
    url(r'^node/(?P<node_id>\d+)/create/$', 'create_topic', name='create_topic'),
    url(r'collected-view/$', 'collected_view', name='collected_view'),
    url(r'^search/(?P<keyword>.*?)/$', 'search', name='search'),

    url(r'^recent/$', 'recent', name='recent'),

    url(r'^previewer/$', 'previewer', name='previewer'),
    url(r'getverifycode/$', 'verifycode', name='verifycode'),


)

cqt/urls.py
from django.conf.urls import patterns, url


urlpatterns = patterns('',
    url(r'^$', 'cqt.views.home', name='home'),
    url(r'^account/$', 'cqt.views.account', name='register'),
)

ddbid/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf.urls.static import static

from bbs import forum
import bbs
from ddbid import settings


admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'ddbid.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^bbs/', include('bbs.forum.urls')),
    url(r'^user/', include('bbs.account.urls')),
    url(r'^', include('searcher.urls')),
    url(r'^api/forum/', include(bbs.forum.urls.api_urlpatterns)),
    url(r'^panel/', include('bbs.panel.urls', namespace='panel', app_name='panel')),
    url(r'^emoji/', include('emoji.urls')),
)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

emoji/urls.py
from django.conf.urls import patterns, url

from .views import EmojiJSONListView

urlpatterns = patterns('',
    url(r'^all.json$', EmojiJSONListView.as_view(), name='list.json'),
)

bbs/forum/models.py
from django.db import models
from django.contrib.auth.models import User
import markdown
import re
from django.core.urlresolvers import reverse
from searcher.models import UserInformation
# Create your models here.


class topic(models.Model):
    user = models.ForeignKey(User, related_name='topics')
    title = models.CharField(max_length=160)
    content = models.TextField(blank=True, null=True)
    content_rendered = models.TextField(blank=True, null=True)
    click = models.IntegerField(default=0)
    reply_count = models.IntegerField(default=0)
    node = models.ForeignKey('node', related_name='topics')
    time_created = models.DateTimeField(auto_now_add=True)
    last_replied = models.DateTimeField(blank=True, null=True)
    deleted = models.BooleanField(default=False)
    order = models.IntegerField(default=10)
    hot_flag = models.BooleanField(default=False)
    essence_flag = models.BooleanField(default=False)
    
    class Meta():
        ordering = ['order', '-time_created']

    def __unicode__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.id:
            new = True
        else:
            new = False
        if not self.content:
            self.content = ''
        self.content_rendered = markdown.markdown(self.content, ['codehilite'],
                                                  safe_mode='escape')
        self.reply_count = self.post_set.filter(deleted=False).count()
        if self.reply_count:
            self.last_replied = self.post_set.filter(deleted=False).latest('time_created').time_created
        to = []
        for u in re.findall(r'@(.*?)\s', self.content_rendered):
            try:
                user = User.objects.get(username=u)
            except:
                pass
            else:
                to.append(user)
                self.content_rendered = re.sub('@%s' % (u),
                                               '@<a href="%s" class="mention">%s</a>'
                                               % (reverse('user_info',
                                                          kwargs={'user_id': user.id}),
                                                  u),
                                               self.content_rendered)
        super(topic, self).save(*args, **kwargs)
        if to and new:
            for t in to:
                m = mention()
                m.sender = self.user
                m.receiver = t
                m.topic = self
                m.save()

        if new:
            self.last_replied = self.time_created
            self.save()


class node(models.Model):
    theme = models.ForeignKey('theme', related_name='nodes')
    title = models.CharField(max_length=12)
    description = models.TextField(blank=True)

    def __unicode__(self):
        return self.title

class theme(models.Model):
    title = models.CharField(max_length=12)
    description = models.TextField(blank=True)

    def __unicode__(self):
        return self.title

class topic_collect(models.Model):
    user = models.ForeignKey(User, related_name='topic_collects')
    topic = models.ForeignKey(topic, related_name='topic_collects')
    deleted = models.BooleanField(default=False)


class post(models.Model):
    user = models.ForeignKey(User, related_name='posts')
    topic = models.ForeignKey('topic')
    content = models.TextField()
    content_rendered = models.TextField()
    time_created = models.DateTimeField(auto_now_add=True)
    deleted = models.BooleanField(default=False)

    class Meta():
        ordering = ['time_created']

    def __unicode__(self):
        return str(self.id) + self.topic.title

    def save(self, *args, **kwargs):
        if not self.id:
            new = True
        else:
            new = False
        if not self.content:
            self.content = ''
        self.content_rendered = markdown.markdown(self.content, ['codehilite'],
                                                  safe_mode='escape')
        to = []
        for u in re.findall(r'@(.*?)\s', self.content_rendered):
            try:
                user = User.objects.get(username=u)
            except:
                pass
            else:
                to.append(user)
                self.content_rendered = re.sub('@%s' % (u),
                                               '@<a href="%s" class="mention">%s</a>'
                                               % (reverse('user_info',
                                                          kwargs={'user_id': user.id}),
                                                  u),
                                               self.content_rendered)
        super(post, self).save(*args, **kwargs)
        if to and new:
            for t in to:
                m = mention()
                m.sender = self.user
                m.receiver = t
                m.post = self
                m.topic = self.topic
                m.save()
        self.topic.save()


class notification(models.Model):
    sender = models.ForeignKey(User, related_name='sent_notifications')
    receiver = models.ForeignKey(User, related_name='received_nofitications')
    topic = models.ForeignKey(topic, blank=True, null=True)
    content = models.TextField(blank=True, null=True)
    read = models.BooleanField(default=True)
    time_created = models.DateTimeField(auto_now_add=True)


class mention(models.Model):
    sender = models.ForeignKey(User, related_name='sent_mentions')
    receiver = models.ForeignKey(User, related_name='received_mentions')
    post = models.ForeignKey(post, blank=True, null=True)
    topic = models.ForeignKey(topic, blank=True, null=True)
    content = models.TextField(blank=True, null=True)
    read = models.BooleanField(default=False)
    time_created = models.DateTimeField(auto_now_add=True)


class appendix(models.Model):
    topic = models.ForeignKey(topic)
    time_created = models.DateTimeField(auto_now_add=True)
    content = models.TextField()
    content_rendered = models.TextField()

    def __unicode__(self):
        return self.topic.title + '-Appendix'

    def save(self, *args, **kwargs):
        if not self.content:
            self.content = ''
        self.content_rendered = markdown.markdown(self.content, ['codehilite'],
                                                  safe_mode='escape')
        super(appendix, self).save(*args, **kwargs)

emoji/models.py
import os
import re
import struct
from sys import version_info

from django.contrib.staticfiles.storage import staticfiles_storage

try:
    from ._unicode_characters import UNICODE_ALIAS
except ImportError as exc:
    UNICODE_ALIAS = {}


from . import settings

__all__ = ('Emoji',)


UNICODE_WIDE = True
try:
    unichr(0x0001f48b)
except ValueError:  # pragma: no cover
    import unicodedata

    UNICODE_WIDE = False
    UNICODE_SURROGATE_MIN = 55296  # U+D800
    UNICODE_SURROGATE_MAX = 57343  # U+DFFF

    def convert_unicode_surrogates(surrogate_pair):
        return unicodedata.normalize('NFKD', surrogate_pair)
except NameError:
    unichr = chr  # Python3 doesn't have unichr

PYTHON3 = False
if version_info[0] == 3:
    PYTHON3 = True
else:
    from _python2 import hex_to_unicode


class Emoji(object):
    """Test if an emoji exists in the library and returns the URL to it.
    Also can add emojis to a text if they match the pattern :emoticon:.

    Usage:
    >>> emoji = Emoji()
    >>> 'dog' in emoji
    True
    >>> 'doesntexistatall' in emoji
    False
    >>> emoji['dog']  # Uses staticfiles app internally
    '/static/emoji/img/dog.png'
    >>> emoji.replace("I am a :cat:.")
    'I am a <img src="/static/emoji/img/cat.png" alt="cat" class="emoji">.'

    This class is a singleton and if imported as following an instantiated
    version will be imported.
    >>> from emoji import Emoji
    >>> Emoji['dog']
    '/static/emoji/dog.png'

    """
    _static_path = 'emoji/img'
    _image_path = os.path.join(os.path.dirname(__file__),
                               'static', 'emoji', 'img')
    _instance = None
    _pattern = re.compile(r':([a-z0-9\+\-_]+):', re.I)
    _files = []
    _unicode_characters = UNICODE_ALIAS

    # This character acts as a modifier, if it's ever seen then remove
    # it because the modification is done when converting to an image
    # anyway.
    _unicode_modifiers = (u'\ufe0e', u'\ufe0f')

    # HTML entities regexs
    _html_entities_integer_unicode_regex = re.compile(r'&#([0-9]+);')
    _html_entities_hex_unicode_regex = re.compile(r'&#x([0-9a-f]+);', re.I)

    def __new__(cls, *args, **kwargs):
        if not cls._instance:
            cls._instance = super(Emoji, cls).__new__(cls, *args, **kwargs)

        return cls._instance

    def __init__(self):
        self.names()

    def __contains__(self, value):
        return value in self._files

    def keys(self):
        return self._files

    def __getitem__(self, item):
        if item in self._files:
            return self._static_url(item)

    def _static_url(self, name):
        return staticfiles_storage.url(
            '{0}/{1}.png'.format(self._static_path, name)
        )

    def _image_string(self, filename, alt=None):
        title = ' '.join(filename.split('_'))

        return settings.EMOJI_IMG_TAG.format(
            self._static_url(filename),
            alt or title,
            title,
        )

    @classmethod
    def names(cls):
        """A list of all emoji names without file extension."""
        if not cls._files:
            for f in os.listdir(cls._image_path):
                if(not f.startswith('.') and
                   os.path.isfile(os.path.join(cls._image_path, f))):
                    cls._files.append(os.path.splitext(f)[0])

        return cls._files

    @classmethod
    def replace(cls, replacement_string):
        """Add in valid emojis in a string where a valid emoji is between ::"""
        e = cls()

        def _replace_emoji(match):
            val = match.group(1)
            if val in e:
                return e._image_string(match.group(1))
            else:
                return match.group(0)

        return e._pattern.sub(_replace_emoji, replacement_string)

    @classmethod
    def replace_unicode(cls, replacement_string):
        """This method will iterate over every character in
        ``replacement_string`` and see if it mathces any of the
        unicode codepoints that we recognize. If it does then it will
        replace that codepoint with an image just like ``replace``.

        NOTE: This will only work with Python versions built with wide
        unicode caracter support. Python 3 should always work but
        Python 2 will have to tested before deploy.

        """
        e = cls()
        output = []
        surrogate_character = None

        if settings.EMOJI_REPLACE_HTML_ENTITIES:
            replacement_string = cls.replace_html_entities(replacement_string)

        for i, character in enumerate(replacement_string):
            if character in cls._unicode_modifiers:
                continue

            # Check whether this is the first character in a Unicode
            # surrogate pair when Python doesn't have wide Unicode
            # support.
            #
            # Is there any reason to do this even if Python got wide
            # support enabled?
            if(not UNICODE_WIDE and not surrogate_character and
               ord(character) >= UNICODE_SURROGATE_MIN and
               ord(character) <= UNICODE_SURROGATE_MAX):
                surrogate_character = character
                continue

            if surrogate_character:
                character = convert_unicode_surrogates(
                    surrogate_character + character
                )
                surrogate_character = None

            name = e.name_for(character)
            if name:
                if settings.EMOJI_ALT_AS_UNICODE:
                    character = e._image_string(name, alt=character)
                else:
                    character = e._image_string(name)

            output.append(character)

        return ''.join(output)

    @classmethod
    def name_for(cls, character):
        for modifier in cls._unicode_modifiers:
            character = character.replace(modifier, '')

        return cls._unicode_characters.get(character, False)

    @classmethod
    def replace_html_entities(cls, replacement_string):
        """Replaces HTML escaped unicode entities with their unicode
        equivalent. If the setting `EMOJI_REPLACE_HTML_ENTITIES` is
        `True` then this conversation will always be done in
        `replace_unicode` (default: True).

        """
        def _hex_to_unicode(hex_code):
            if PYTHON3:
                hex_code = '{0:0>8}'.format(hex_code)
                as_int = struct.unpack('>i', bytes.fromhex(hex_code))[0]
                return '{0:c}'.format(as_int)
            else:
                return hex_to_unicode(hex_code)

        def _replace_integer_entity(match):
            hex_val = hex(int(match.group(1)))

            return _hex_to_unicode(hex_val.replace('0x', ''))

        def _replace_hex_entity(match):
            return _hex_to_unicode(match.group(1))

        # replace integer code points, &#65;
        replacement_string = re.sub(
            cls._html_entities_integer_unicode_regex,
            _replace_integer_entity,
            replacement_string
        )
        # replace hex code points, &#x41;
        replacement_string = re.sub(
            cls._html_entities_hex_unicode_regex,
            _replace_hex_entity,
            replacement_string
        )

        return replacement_string

emoji/views.py
import json

from django.http import HttpResponse
from django.views.generic import View

from . import Emoji


class EmojiJSONListView(View):
    def get(self, request, *args, **kwargs):
        return HttpResponse(json.dumps(dict(Emoji)),
                            content_type='application/json')

bbs/forum/templates/forum/append.html
{% extends 'base-with-sidebar.html' %}
{% load i18n %}
{% block left %}
<div class="bbs_content bbs_post mt10">
    <div class="bbs_post_add">
		<p class="panel-title">
		  添加附言--<a href="{% url 'bbsindex' %}">首页</a>-<a href="{% url 'node_view' topic.node.id %}">{{ topic.node.title }}</a>-{{topic.title}}
		</p>
	</div>
	<div class="panel-body">
		{% if messages %}
		<div class="messages">
			{% for message in messages %}
			<p class="text-{{ message.tags }}">
				{{ message }}
			</p>
			{% endfor %}
		</div>
		{% endif %}
		<form class="form" action="{% url 'add_appendix' topic.id%}" method="post">
			{% csrf_token %}
			<div class="bbs_post_con textbox ">
				<label class="sr-only" for="content">{% trans 'content' %}</label>
				<textarea placeholder="{% trans 'content' %}"  class="bbs_post_txt" id="content" name="content"></textarea>
				<input type="submit" class="bbs_post_btn"   value="提交" />
			</div>
		</form>
		<div class="previewer">

		</div>
	</div>
</div><!--end reply panel-->
{% endblock %}
{% block right %}
{% include 'user-panel.html' %}
{% include 'advert.html' %}
{% include 'hot-topic.html' %}
{% include 'essence_topic.html' %}
{% include 'friendly-link.html' %}
{% endblock %}
{% block footer_ext %}
<script src="{{STATIC_URL}}js/previewer.js"></script>
{% endblock %}

bbs/forum/templates/forum/collect-user-view.html
{% extends 'base-with-sidebar.html' %}
{% block top_title %}
    {% include 'top_title1.html' %}
{% endblock %}
{% block header_ext%}
    <meta name="keywords" content="" />
    <meta name="description" content="" />
{% endblock %}
{% block left %}
{% include 'collect-user-list.html' %}
{% endblock %}
{% block right %}
{% include 'user-panel.html' %}
{% include 'advert.html' %}
{% include 'hot-topic.html' %}
{% include 'essence_topic.html' %}
{% include 'friendly-link.html' %}
{% endblock %}

bbs/forum/templates/forum/collect-view.html
{% extends 'base-with-sidebar.html' %}
{% block top_title %}
    {% include 'top_title1.html' %}
{% endblock %}
{% block header_ext%}
    <meta name="keywords" content="" />
    <meta name="description" content="" />
{% endblock %}
{% block left %}
{% include 'collect-list.html' %}
{% endblock %}
{% block right %}
{% include 'user-panel.html' %}
{% include 'advert.html' %}
{% include 'hot-topic.html' %}
{% include 'essence_topic.html' %}
{% include 'friendly-link.html' %}
{% endblock %}

bbs/forum/templates/forum/edit-topic.html
{% extends 'base-with-sidebar.html' %}
{% load i18n %}
{% block left %}
<div class="bbs_content bbs_post mt10">
    <div class="bbs_post_add">
        {% trans 'edit topic' %}--<a href="{% url 'bbsindex' %}">首页</a>-<a href="{% url 'node_view' topic.node.id %}">{{ topic.node.title }}</a>-{{topic.title}}
    </div>
    <div class="panel-body">
    	{% if messages %}
		<div class="messages">
			{% for message in messages %}
			<p class="text-{{ message.tags }}">
				{{ message }}
			</p>
			{% endfor %}
		</div>
		{% endif %}
        {% if request.user.is_authenticated %}
        <form class="form" action="{% url 'edit_topic' topic.id%}" method="post">
            {% csrf_token %}
            <div class="bbs_post_con textbox ">
                <div style="margin-bottom: 6px"><label class="sr-only" for="content">标题</label></div>
                <input placeholder="{% trans 'title' %}" value="{{topic.title}}" type="text" class="bbs_post_txt" id="title" name="title" />
                <div style="margin-bottom: 6px"><label class="sr-only" for="content">{% trans 'content' %}</label><a id='addemoji'onclick="show_emoji()" style="padding-left: 5px;"><img src="/static/emoji/img/grinning.png" title="添加表情" style="width: 23px;height: 23px;" /></a></div>
                {% include "emoji.html" %}
                <textarea placeholder="{% trans 'content' %}"  class="bbs_post_textarea" id="content" name="content">{{topic.content}}</textarea>
                <input type="submit" class="bbs_post_btn"  value="提交" />
                {% include 'remind.html' %}
            </div>
        </form>
        
        <div class="previewer">
        </div>
        {% endif %}
    </div>
</div><!--end reply panel-->
{% endblock %}
{% block right %}
{% include 'user-panel.html' %}
{% include 'advert.html' %}
{% include 'hot-topic.html' %}
{% include 'essence_topic.html' %}
{% include 'friendly-link.html' %}
{% endblock %}
{% block footer_ext %}
<script src="{{STATIC_URL}}js/previewer.js"></script>
{% endblock %}

bbs/forum/templates/forum/topic.html
{% extends 'base-with-sidebar.html' %}
{% load i18n %}
{% block left %}
{% load humanize %}
{% load pagination_tags %}
{% load settingsvalue %}
{% load emoji_tags %}
<div class="bbs_content  mt10">
	<div class="bbs_con_box">
        <div class="bbs_add"><a href="{% url 'bbsindex' %}">首页</a> ><a href="{% url 'node_view' topic.node.id %}">{{topic.node.title}}</a></div>
        <div class="bbs_ideas mt10">
           <div class="bbs_ideas_left fl">
               <h2>{{topic.title}}</h2>
               <p>By {{ topic.user.username }} at {{ topic.time_created|date:"Y-m-j  H:i:s"  }}
					{% if request.user == topic.user%}
					<span class="bbs_operate"><a class="label-success label" href="{% url 'add_appendix' topic.id %}">{% trans 'add appendix' %}</a></span>
					{% endif %}
                    {% if request.user.is_authenticated %}
                        {% if request.user.is_superuser or topic.user == request.user %}
                        <span class="bbs_operate"><a class="label-warning label" href="{% url 'edit_topic' topic.id %}">{% trans 'edit' %}</a></span>
                          {% if request.user.is_superuser %}
                            <span class="bbs_operate"><a class="label-danger label" href="{% url 'delete_topic' topic.id %}">{% trans 'delete' %}</a></span>
                          {% endif %}
                        {% else %}
                                {% if collected == True %}
                                   <span class="bbs_operate"><a class="label-warning label" href="{% url 'collect_topic' topic.id %}">关注该主题</a></span>
                                {% else %}
                                   <span class="bbs_operate"><a class="label-warning label" href="{% url 'collect_topic' topic.id %}">取消关注</a></span>
                                {% endif %}
                         {% endif %}
                    {% endif %}
			   </p>
           </div>
             {% ifequal user.id None %}
              <div class="bbs_ideas_right fr"><a href="{% url 'login' %}"><img src="{{topic.user.userinformation.photo_url}}" /></a></div>
             {% else %}
              <div class="bbs_ideas_right fr"><a href="{% url 'user_info' topic.user.id %}"><img src="{{topic.user.userinformation.photo_url}}" /></a></div>
             {% endifequal %}
        </div>
	</div>
	<div class="bbs_article">
		{{topic.content|safe|emoji_replace}}
    </div>
	{% if topic.appendix_set.all %}
	<ul class="list-group">
		{% for a in topic.appendix_set.all %}
		<div class="list-group-item list-appendix-item">
			<p class="appendix-meta">
				{% blocktrans with number=forloop.counter %}appendix {{number}}{% endblocktrans %} {{a.time_created|naturaltime}}
			</p>
			<div class="bbs_article">{{a.content | safe|emoji_replace}}</div>
		</div>
		{% endfor %}
	</ul>
	{% endif %}
    <div class="bbs_bottom">
                	<div class="bbs_click fr">{{ topic.click }}次点击</div>
                	<!-- JiaThis Button BEGIN -->
                    <div class="jiathis_style">
                        <a class="jiathis_button_qzone"></a>
                        <a class="jiathis_button_tsina"></a>
                        <a class="jiathis_button_tqq"></a>
                        <a class="jiathis_button_weixin"></a>
                        <a class="jiathis_button_renren"></a>
                        <a class="jiathis_button_xiaoyou"></a>
                        <a href="http://www.jiathis.com/share" class="jiathis jiathis_txt jtico jtico_jiathis" target="_blank"></a>
                        <a class="jiathis_counter_style"></a>
                    </div>
                    <script type="text/javascript" src="http://v3.jiathis.com/code/jia.js" charset="utf-8"></script>
                    <!-- JiaThis Button END -->
    </div>
</div><!--end content panel-->

<div class="bbs_reply mt10 bbs_box">
    <div class="bbs_reply_num">{{ topic.reply_count }}&nbsp;&nbsp;回复&nbsp;&nbsp;|&nbsp;&nbsp;直到&nbsp;&nbsp;{{ topic.last_replied|date:"Y-m-j  H:i:s" }}</div>
	{% if topic.reply_count != 0 %}
		{% autopaginate posts 18 %}
		{% for r in posts %}
            <dl class="bbs_reply_list">
               {% ifequal user.id None  %}
                <dt><a href="{% url 'login' %}"><img title="{{r.user.username}}" src="{{r.user.userinformation.photo_url}}" /></a></dt>
               {% else %}
                <dt><a href="{% url 'user_info' r.user.id %}"><img title="{{r.user.username}}" src="{{r.user.userinformation.photo_url}}" /></a></dt>
               {% endifequal %}
                <dd>
                 {% ifequal user.id None  %}
                   <p><span class="bbs_reply_number fr">{{ forloop.counter }}</span><a href="{% url 'login' %}" class="bbs_username">{{r.user.username}}</a>{{ r.time_created|date:"Y-m-j  H:i:s" }}
                 {% else %}
                   <p><span class="bbs_reply_number fr">{{ forloop.counter }}</span><a href="{% url 'user_info' r.user.id %}" class="bbs_username">{{r.user.username}}</a>{{ r.time_created|date:"Y-m-j  H:i:s" }}
                 {% endifequal %}
                      {% if request.user.is_authenticated %}
					     <a href="#create_reply" data-user="{{r.user.username}}" class="label-info label pull-right reply-btn" onclick="{Javascript:send_messige()}" >回复</a>
					  {% endif %}
                   </p>
                   <div class="bbs_reply_con">
                      {{r.content|safe|emoji_replace}}
                   </div>
                </dd>
            </dl>
		{% endfor %}
     <dl class="bbs_reply_list"></dl>
	 <div class="panel-footer">
		{% paginate %}
	 </div>
	{% else %}
	<div class="panel-body">
		<div class="alert alert-info">
			{% trans 'no replies yet' %}
		</div>
	</div>
	{% endif %}
</div><!--end reply panel-->
<div class="bbs_publish bbs_box mt10" id="create_reply">
    {% if messages %}
		<div class="messages">
			{% for message in messages %}
			<p class="text-{{ message.tags }}">
				{{ message }}
			</p>
			{% endfor %}
		</div>
    {% endif %}
    {% if request.user.is_authenticated %}
    <div class="bbs_hd"><a href="#" class="bbs_backtop fr">回到顶部</a><h3>快速回复  <a id='addemoji'onclick="show_emoji()"><img src="/static/emoji/img/grinning.png" title="添加表情" style="width: 23px;height: 23px;" /></a></h3></div>
    {% include 'emoji.html' %}
    <form class="form" action="{% url 'create_reply' topic.id%}" method="post">
	   {% csrf_token %}
        <div class="bbs_bd">
           <textarea id="content" name="content"></textarea>
            <div style="padding-top: 5px">
            <input type="submit" class="bbs_post_btn"   value="回复" />
            </div>
                <li class="yzm" >
                   <div style="padding-top: 5px">
                   <input name="log_code" id="log_code" type="text" placeholder="验证码"
                          onfocus="$('#code_pic').click();yzmshow()" />

                   <a href="javascript:void(0);" id="yzm" style="display: none"><img id="code_pic"
                     onclick="this.setAttribute('src',{% url 'verifycode' %} + '?nocache='+Math.random());"
                     src="{% url 'verifycode' %}"/></a>
                   {% include 'remind.html' %}
                   </div>
                </li>
        </div>
    </form>
    {% else %}
    {% endif %}
</div>
{% endblock %}

{% block right %}
{% include 'user-panel.html' %}
{% include 'advert.html' %}
{% include 'hot-topic.html' %}
{% include 'essence_topic.html' %}
{% include 'friendly-link.html' %}
{% endblock %}
{% block footer_ext %}
<script src="/static/js/previewer.js"></script>
<script src="/static/js/mention.js"></script>
<script type="text/javascript">
    function insert_img(){
        var tc = document.getElementById("content");
        var tclen = tc.value.length;
        tc.focus();
        str = "<img>在此输入图片链接</img>";
        tc.value = tc.value.substr(0,tc.selectionStart)+str+tc.value.substring(tc.selectionStart,tclen);

    }
</script>
{% endblock %}