bbs/panel/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('bbs.panel.views',
    url(r'^$', 'index', name='index'),

    url(r'^user/all/$', 'user_manage', name="user_manage"),
    url(r'^user/(?P<uid>\d+)/edit/$', 'user_edit', name="user_edit"),
    url(r'^user/all/data-ss/$', 'user_table_ss', name="user_table_ss"),

    url(r'^node/all/$', 'node_manage', name="node_manage"),
    url(r'^node/create/$', 'node_create', name="node_create"),
    url(r'^node/all/data-ss/$', 'node_table_ss', name="node_table_ss"),
    url(r'^node/(?P<node_id>\d+)/edit/$', 'node_edit', name="node_edit"),

    url(r'^topic/all/$', 'topic_manage', name="topic_manage"),
    #url(r'^topic/(?P<topic_id>\d+)/edit/$', 'topic_edit', name="topic_edit"),
    url(r'^topic/all/data-ss/$', 'topic_table_ss', name="topic_table_ss"),
    url(r'^topic/(?P<topic_id>\d+)/$', 'topic_edit', name="topic_edit"),

    url(r'^ajax/node/$', 'node_title_ajax', name="node_title_ajax"),
    url(r'^ajax/topic/bulk-delete/$', 'topic_bulk_delete', name="topic_bulk_delete"),
)

cqt/urls.py
from django.conf.urls import patterns, url


urlpatterns = patterns('',
    url(r'^$', 'cqt.views.home', name='home'),
    url(r'^account/$', 'cqt.views.account', name='register'),
)

ddbid/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf.urls.static import static

from bbs import forum
import bbs
from ddbid import settings


admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'ddbid.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^bbs/', include('bbs.forum.urls')),
    url(r'^user/', include('bbs.account.urls')),
    url(r'^', include('searcher.urls')),
    url(r'^api/forum/', include(bbs.forum.urls.api_urlpatterns)),
    url(r'^panel/', include('bbs.panel.urls', namespace='panel', app_name='panel')),
    url(r'^emoji/', include('emoji.urls')),
)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

emoji/urls.py
from django.conf.urls import patterns, url

from .views import EmojiJSONListView

urlpatterns = patterns('',
    url(r'^all.json$', EmojiJSONListView.as_view(), name='list.json'),
)

bbs/panel/models.py
from django.db import models

# Create your models here.

bbs/panel/views.py
# -*- coding: utf-8 -*-
import json

from django.template import RequestContext
from django.shortcuts import render_to_response
from django.utils.translation import ugettext as _
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import user_passes_test
from django.db.models import Q

from bbs.forum.models import node, topic

# Create your views here.


@user_passes_test(lambda u: u.is_superuser, login_url=reverse('signin'))
def index(request):
    return render_to_response('panel/index.html', {'title': _('home')})


@user_passes_test(lambda u: u.is_superuser)
def user_manage(request):
    return render_to_response('panel/user-manage.html', {'title': _('user management')})


@user_passes_test(lambda u: u.is_superuser, login_url=reverse('signin'))
def user_table_data(request):
    data = {}
    data['aaData'] = []
    for u in User.objects.all():
        info_list = [u.username,u.email]
        data['aaData'].append(info_list)
    return HttpResponse(json.dumps(data))


@user_passes_test(lambda u: u.is_superuser, login_url=reverse('signin'))
def user_table_ss(request):
    fields = ['id','username', 'email']
    order_dir = request.GET.get('sSortDir_0')
    order_field = int(request.GET.get('iSortCol_0'))
    if order_dir == 'asc':
        order_by = '%s' % fields[order_field]
    else:
        order_by = '-%s' % fields[order_field]
    length = int(request.GET.get('iDisplayLength',10))
    key = request.GET.get('sSearch')
    start = int(request.GET.get('iDisplayStart',0))
    if key:
        if key.isdigit():
            condition = Q(email__contains=key)|Q(username__contains=key)|Q(id=key)
        else:
            condition = Q(email__contains=key)|Q(username__contains=key)
        users = User.objects.filter(condition).order_by(order_by)
    else:
        users = User.objects.all().order_by(order_by)
    data = {}
    data['aaData'] = []
    data['iTotalDisplayRecords'] = len(users)
    users = users[start:start+length]
    data['iTotalRecords'] = User.objects.count()
    for u in users:
        info_list = [u.id, u.username, u.email]
        info_list.append('<a href="%s" class="label label-success">%s</a>' % \
                (
                    reverse('panel:user_edit', kwargs={'uid': u.id}),
                _('edit')
                )
            )
        data['aaData'].append(info_list)
    return HttpResponse(json.dumps(data))



@user_passes_test(lambda u: u.is_superuser, login_url=reverse('signin'))
def user_edit(request,uid):
    u = User.objects.get(id=uid)
    if request.method == 'GET':
        return render_to_response('panel/user-edit.html',{'title': _('edit user'), 'user': u},
               context_instance=RequestContext(request))
    elif request.method == 'POST':
        data = request.POST
        username = data['username']
        email = data.get('email', False)
        password = data.get('password', False)
        active = data.has_key('active')
        admin = data.has_key('admin')
        nickname = data.get('nickname')
        location = data.get('location')
        website = data.get('website')
        use_gravatar = data.has_key('gravatar')
        u.username = username
        u.email = email
        if password:
            u.set_password(password)
        u.is_active = active
        u.is_superuser = admin
        u.save()
        p = u.profile
        p.nickname = nickname
        p.website = website
        p.location = location
        p.use_gravatar = use_gravatar
        p.save()
        return HttpResponseRedirect(reverse('panel:user_edit', args=[uid]))


@user_passes_test(lambda u: u.is_superuser, login_url=reverse('signin'))
def node_manage(request):
    return render_to_response('panel/node-manage.html', {'title': _('node management')})


@user_passes_test(lambda u: u.is_superuser, login_url=reverse('signin'))
def node_table_ss(request):
    fields = ['id','title']
    order_dir = request.GET.get('sSortDir_0')
    order_field = int(request.GET.get('iSortCol_0'))
    if order_dir == 'asc':
        order_by = '%s' % fields[order_field]
    else:
        order_by = '-%s' % fields[order_field]
    length = int(request.GET.get('iDisplayLength',10))
    key = request.GET.get('sSearch')
    start = int(request.GET.get('iDisplayStart',0))
    if key:
        if key.isdigit():
            condition = Q(title__contains=key)|Q(id=key)
        else:
            condition = Q(title__contains=key)
        nodes = node.objects.filter(condition).order_by(order_by)
    else:
        nodes = node.objects.all().order_by(order_by)
    data = {}
    data['aaData'] = []
    data['iTotalDisplayRecords'] = len(nodes)
    nodes = nodes[start:start+length]
    data['iTotalRecords'] = node.objects.count()
    for n in nodes:
        info_list = [n.id, n.title]
        info_list.append('<a href="%s" class="label label-success">%s</a>' %\
                (
                    reverse('panel:node_edit', kwargs={'node_id': n.id}),
                    _('edit')
                )
            )
        data['aaData'].append(info_list)
    return HttpResponse(json.dumps(data))


@user_passes_test(lambda u: u.is_superuser, login_url=reverse('signin'))
def node_edit(request,node_id):
    n = node.objects.get(id=node_id)
    if request.method == 'GET':
        return render_to_response('panel/node-edit.html', {'title': _('edit node'), 'node': n},
               context_instance=RequestContext(request))
    elif request.method == 'POST':
        data = request.POST
        title = data.get('title', 'empty')
        description = data.get('description', None)
        n.title = title
        n.description = description
        n.save()
        return HttpResponseRedirect(reverse('panel:node_edit', args=[n.id]))


@user_passes_test(lambda u: u.is_superuser, login_url=reverse('signin'))
def node_create(request):
    if request.method == 'GET':
        return render_to_response('panel/node-create.html', {'title': _('create node')},
               context_instance=RequestContext(request))
    elif request.method == 'POST':
        n = node()
        data = request.POST
        title = data.get('title', 'empty')
        description = data.get('description', None)
        n.title = title
        n.description = description
        n.save()
        return HttpResponseRedirect(reverse('panel:node_manage'))


@user_passes_test(lambda u: u.is_superuser, login_url=reverse('signin'))
def topic_manage(request):
    return render_to_response('panel/topic-manage.html', {'title': _('topic management')})


@user_passes_test(lambda u: u.is_superuser, login_url=reverse('signin'))


def topic_edit(request,topic_id):
    t = topic.objects.get(id=topic_id)
    if request.method == 'GET':
        return render_to_response('panel/topic-edit.html',{'title': _('edit topic'), 'topic': t},
               context_instance=RequestContext(request))
    elif request.method == 'POST':
        data = request.POST
        title = data['title']
        node_title = data['node']
        content = data['content']
        order = data['order']
        n = node.objects.get(title=node_title)
        t.title = title
        t.node = n
        t.content = content
        t.order = order
        t.save()
        return HttpResponseRedirect(reverse('panel:topic_edit', args=[t.id]))


@user_passes_test(lambda u: u.is_superuser, login_url=reverse('signin'))
def topic_table_ss(request):
    fields = ['id', 'title', 'user__username', 'node__title']
    order_dir = request.GET.get('sSortDir_0')
    order_field = int(request.GET.get('iSortCol_0'))
    if order_dir == 'asc':
        order_by = '%s' % fields[order_field]
    else:
        order_by = '-%s' % fields[order_field]
    length = int(request.GET.get('iDisplayLength',10))
    key = request.GET.get('sSearch')
    start = int(request.GET.get('iDisplayStart',0))
    if key:
        if key.isdigit():
            condition = Q(title__contains=key)|Q(node__title__contains=key)|Q(user__username__contains=key)|Q(id=key)
        else:
            condition = Q(title__contains=key)|Q(node__title__contains=key)|Q(user__username__contains=key)
        topics = topic.objects.filter(condition, deleted=False).order_by(order_by)
    else:
        topics = topic.objects.filter(deleted=False).order_by(order_by)
    data = {}
    data['aaData'] = []
    data['iTotalDisplayRecords'] = len(topics)
    topics = topics[start:start+length]
    data['iTotalRecords'] = topic.objects.count()
    for t in topics:
        info_list = [t.id, t.title, t.user.username, t.node.title]
        info_list.append('<a href="%s" class="label label-success">%s</a>' % \
                (
                    reverse('panel:topic_edit', kwargs={'topic_id': t.id}),
                    _('edit')
                )
            )
        data['aaData'].append(info_list)
    return HttpResponse(json.dumps(data))


@user_passes_test(lambda u: u.is_superuser, login_url=reverse('signin'))
def node_title_ajax(request):
    key = request.GET.get('query')
    condition = Q(title__contains=key)
    nodes = node.objects.filter(condition)
    data = {}
    data['suggestions'] = []
    for n in nodes.all():
        data['suggestions'].append(n.title)
    return HttpResponse(json.dumps(data))


@user_passes_test(lambda u: u.is_superuser, login_url=reverse('signin'))
def topic_bulk_delete(request):
    ids = request.GET['ids']
    ids = ids.split(',')
    ts = []
    for i in ids:
        t = topic.objects.get(id=i)
        t.deleted = True
        t.save()
        ts.append(t)
    return HttpResponse(ts)

bbs/panel/templates/panel/base.html
{% load settingsvalue %}
{% load i18n %}
<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>{{title}}-{% trans 'admin' %}-{% conf_value "sitename" %}</title>

    <!-- Core CSS - Include with every page -->
    <link href="/static/panel/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/panel/font-awesome/css/font-awesome.css" rel="stylesheet">

    <!-- Page-Level Plugin CSS - Dashboard -->
    <link href="/static/panel/css/plugins/morris/morris-0.4.3.min.css" rel="stylesheet">
    <link href="/static/panel/css/plugins/timeline/timeline.css" rel="stylesheet">
    <link href="/static/css/base.css" rel="stylesheet">

    <!-- SB Admin CSS - Include with every page -->
    <link href="/static/panel/css/sb-admin.css" rel="stylesheet">

</head>

<body>

    <div id="wrapper">

        <nav class="navbar navbar-default navbar-fixed-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">{% conf_value "sitename" %}-{% trans 'admin' %}</a>
            </div>
            <!-- /.navbar-header -->

            
            <!-- /.navbar-top-links -->

            <div class="navbar-default navbar-static-side" role="navigation">
                <div class="sidebar-collapse">
                    <ul class="nav" id="side-menu">
                        
                        <li>
                        <a href="{% url 'panel:index' %}"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
                        </li>

                        <li>
                        <a href="#"><i class="fa fa-user fa-fw"></i> {% trans 'user management' %}<span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level collapse">
                            <li>
                            <a href="{% url 'panel:user_manage' %}"><i class="fa fa-users fa-fw"></i> {% trans 'all users' %}</a>
                            </li>
                        </ul>
                        <!-- /.nav-second-level -->
                        </li> 

                        <li>
                        <a href="#"><i class="fa fa-square fa-fw"></i> {% trans 'node management' %}<span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level collapse">
                            <li>
                            <a href="{% url 'panel:node_manage' %}"><i class="fa fa-sitemap fa-fw"></i> {% trans 'all nodes' %}</a>
                            </li>

                            <li>
                            <a href="{% url 'panel:node_create' %}"><i class="fa fa-plus fa-fw"></i> {% trans 'create node' %}</a>
                            </li>
                        </ul>
                        <!-- /.nav-second-level -->
                        </li>

                        <li>
                        <a href="#"><i class="fa fa-comment fa-fw"></i> {% trans 'content management' %}<span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level collapse">
                            <li>
                            <a href="{% url 'panel:topic_manage' %}"><i class="fa fa-comments fa-fw"></i> {% trans 'all topics' %}</a>
                            </li>
                        </ul>
                        <!-- /.nav-second-level -->
                        </li>

                    </ul>
                    <!-- /#side-menu -->
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>

        <div id="page-wrapper">
            {% block main %}
            {% endblock %}
        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- Core Scripts - Include with every page -->
    <script src="/static/panel/js/jquery-1.10.2.js"></script>
    <script src="/static/panel/js/bootstrap.min.js"></script>
    <script src="/static/panel/js/plugins/metisMenu/jquery.metisMenu.js"></script>
    <script src="/static/panel/js/autocomplete.js"></script>

    <!-- SB Admin Scripts - Include with every page -->
    <script src="/static/panel/js/sb-admin.js"></script>

    {% block footer_ext %}{% endblock %}
</body>

</html>

bbs/panel/templates/panel/index.html
{% extends 'panel/base.html' %}

bbs/panel/templates/panel/node-create.html
{% extends 'panel/base.html' %}
{% load i18n %}

{% block main %}
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">{% trans 'create node' %}</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <strong>{% trans 'new node' %}</strong>
            </div>
            <div class="panel-body">
                <form role="form" method="post" action="{% url 'panel:node_create'%}">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="form-group">
                                <label>{% trans 'node title' %}</label>
                                <input class="form-control" name="title" value="{{node.title}}">
                            </div>
                            <div class="form-group">
                                <label>{% trans 'node description' %}</label>
                                <textarea class="form-control" name="description" rows="3">{{node.description}}</textarea>
                            </div>
                        </div>
                        <!-- /.col-lg-6 (nested) -->

                        <!-- /.col-lg-6 (nested) -->
                    </div>
                    <!-- /.row (nested) -->
                    <button type="submit" class="btn btn-danger">{% trans 'submit' %}</button>
                </form>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>
{% endblock %}

bbs/panel/templates/panel/node-edit.html
{% extends 'panel/base.html' %}

{% load i18n %}
{% block main %}
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">{% trans 'edit node' %}</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <strong>{{node.title}}</strong>
            </div>
            <div class="panel-body">
                <form role="form" method="post" action="{% url 'panel:node_edit' node.id %}">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="form-group">
                                <label>{% trans 'node title' %}</label>
                                <input class="form-control" name="title" value="{{node.title}}">
                            </div>
                            <div class="form-group">
                                <label>{% trans 'node description' %}</label>
                                <textarea class="form-control" name="description" rows="3">{{node.description}}</textarea>
                            </div>
                        </div>
                        <!-- /.col-lg-6 (nested) -->

                        <!-- /.col-lg-6 (nested) -->
                    </div>
                    <!-- /.row (nested) -->
                    <button type="submit" class="btn btn-danger">{% trans 'submit' %}</button>
                </form>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>
{% endblock %}

bbs/panel/templates/panel/node-manage.html
{% extends 'panel/base.html' %}
{% load i18n %}
{% block main %}
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">{% trans 'node management' %}</h1>
    </div>
</div>
    <!-- /.col-lg-12 -->
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                  {% trans 'node management' %} 
                </div>
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class="table table-default table-bordered table-hover" id="database">
                            <thead>
                                <tr>
                                    <th>id</th>
                                    <th>{% trans 'title' %}</th>
                                    <th>{% trans 'edit' %}</th>
                                </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block footer_ext %}

<script src="/static/panel/js/plugins/dataTables/jquery.dataTables.js"></script>
<script src="/static/panel/js/tabletools.js"></script>
<script src="/static/panel/js/plugins/dataTables/dataTables.bootstrap.js"></script>
<script>
$(document).ready(function() {
        $('#database').dataTable({
            "bProcessing": true,
            "bServerSide": true,
            "sAjaxSource": "{% url 'panel:node_table_ss' %}",
            "aoColumnDefs": [
                      { 'bSortable': false, 'aTargets': [ -1 ] }
                          ],
                          "sDom": "<'row'<'col-sm-4'l><'col-sm-4'f><'col-sm-4'T>r>" + "t" + "<'row'<'col-sm-6'i><'col-sm-6'p>>",
            "oTableTools": {
                          "sRowSelect": "multi",
                          "aButtons": [ "select_all", "select_none" ]
                          },
            });
        });
function selected_id(){
    selected_rows = $('tr.active');
    ids = []
    selected_rows.each(
            
            function(){
                ids.push($(this).context.cells[0].childNodes[0].data);
            }
            
        )
    return ids.toString()
}
</script>
{% endblock %}

bbs/panel/templates/panel/topic-edit.html
{% extends 'panel/base.html' %}
{% load i18n %}

{% block main %}
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">{% trans 'edit topic' %}</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <strong>{{topic.title}}</strong>
            </div>
            <div class="panel-body">
                <form role="form" method="post" action="{% url 'panel:topic_edit' topic.id %}">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="form-group">
                                <label>{% trans 'title' %}</label>
                                <input class="form-control" name="title" value="{{topic.title}}">
                            </div>
                            <div class="form-group">
                                <label>{% trans 'author' %}</label>
                                <input class="form-control" name="user" value="{{topic.user.username}}" disabled>
                            </div>
                            <div class="form-group">
                                <label>{% trans 'node' %}</label>
                                <input class="form-control" name="node" id="node-input" value="{{topic.node.title}}">
                            </div>
                            <div class="form-group">
                                <label>{% trans 'content' %}</label>
                                <textarea class="form-control" name="content" rows="10">{{topic.content}}</textarea>
                            </div>
                            <div class="form-group">
                                <label>{% trans 'order(0-99,default:99)'%}</label>
                                <input class="form-control" name="order" value={{topic.order}}>
                            </div>
                        </div>
                        <!-- /.col-lg-6 (nested) -->

                        <!-- /.col-lg-6 (nested) -->
                    </div>
                    <!-- /.row (nested) -->
                    <button type="submit" class="btn btn-danger">{% trans 'submit' %}</button>
                </form>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>
{% endblock %}

{% block footer_ext %}
<style>
.autocomplete-suggestions { border: 1px solid #999; background: #FFF; overflow: auto; }
.autocomplete-suggestion { padding: 2px 5px; white-space: nowrap; overflow: hidden; }
.autocomplete-selected { background: #F0F0F0; }
.autocomplete-suggestions strong { font-weight: normal; color: #3399FF; }
</style>
<script>
$(document).ready(


            $('#node-input').autocomplete(
                
                {
                'serviceUrl': "{% url 'panel:node_title_ajax' %}"
                }

                )

        
        );
</script>
{% endblock %}

bbs/panel/templates/panel/topic-manage.html
{% extends 'panel/base.html' %}
{% load i18n %}
{% block main %}
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">{% trans 'topic management' %}</h1>
    </div>
</div>
    <!-- /.col-lg-12 -->
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    {% trans 'topic management' %}
                </div>
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class="table table-default table-bordered table-hover" id="database">
                            <thead>
                                <tr>
                                    <th>id</th>
                                    <th>{% trans 'title' %}</th>
                                    <th>{% trans 'username' %}</th>
                                    <th>{% trans 'node title' %}</th>
                                    <th>{% trans 'edit' %}</th>
                                </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                    </div>
                    <a class="btn btn-danger" id="bulk-delete">{% trans 'delete selected' %}</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block footer_ext %}

<script src="/static/panel/js/plugins/dataTables/jquery.dataTables.js"></script>
<script src="/static/panel/js/tabletools.js"></script>
<script src="/static/panel/js/plugins/dataTables/dataTables.bootstrap.js"></script>
<script>
$(document).ready(function() {
        $('#database').dataTable({
            "bProcessing": true,
            "bServerSide": true,
            "bPaginate": true,
            "sAjaxSource": "{% url 'panel:topic_table_ss' %}",
            "aoColumnDefs": [
                      { 'bSortable': false, 'aTargets': [ -1 ] }
                          ],
                          "sDom": "<'row'<'col-sm-4'l><'col-sm-4'f><'col-sm-4'T>r>" + "t" + "<'row'<'col-sm-6'i><'col-sm-6'p>>",
            "oTableTools": {
                          "sRowSelect": "multi",
                          "aButtons": [ "select_all", "select_none" ]
                          },
            });
        });
function selected_id(){
    selected_rows = $('tr.active');
    ids = []
    selected_rows.each(
            
            function(){
                ids.push($(this).context.cells[0].childNodes[0].data);
            }
            
        )
    return ids.toString()
}
$(document).ready(
        
        function(){
        
            $('#bulk-delete').click(
                
                function(){
                
                    $.get('{% url "panel:topic_bulk_delete" %}', {'ids': selected_id()});
                    location.reload();
                
                }

                );
        
        }
        
        );
</script>
{% endblock %}

bbs/panel/templates/panel/user-manage.html
{% extends 'panel/base.html' %}
{% load i18n %}
{% block main %}
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">{% trans 'user management' %}</h1>
    </div>
</div>
    <!-- /.col-lg-12 -->
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    {% trans 'all users' %}
                </div>
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class="table table-default table-bordered table-hover" id="database">
                            <thead>
                                <tr>
                                    <th>id</th>
                                    <th>{% trans 'username' %}</th>
                                    <th>{% trans 'email' %}</th>
                                    <th>{% trans 'edit' %}</th>
                                </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block footer_ext %}

<script src="/static/panel/js/plugins/dataTables/jquery.dataTables.js"></script>
<script src="/static/panel/js/tabletools.js"></script>
<script src="/static/panel/js/plugins/dataTables/dataTables.bootstrap.js"></script>
<script>
$(document).ready(function() {
        $('#database').dataTable({
            "bProcessing": true,
            "bServerSide": true,
            "bPaginate": true,
            "sAjaxSource": "{% url 'panel:user_table_ss' %}",
            "aoColumnDefs": [
                      { 'bSortable': false, 'aTargets': [ -1 ] }
                          ],
                          "sDom": "<'row'<'col-sm-4'l><'col-sm-4'f><'col-sm-4'T>r>" + "t" + "<'row'<'col-sm-6'i><'col-sm-6'p>>",
            "oTableTools": {
                          "sRowSelect": "multi",
                          "aButtons": [ "select_all", "select_none" ]
                          },
            });
        });
function selected_id(){
    selected_rows = $('tr.active');
    ids = []
    selected_rows.each(
            
            function(){
                ids.push($(this).context.cells[0].childNodes[0].data);
            }
            
        )
    return ids.toString()
}
</script>
{% endblock %}